### ISSUE TITLE
php-streaming-output-buffering

### ISSUE THREAD

**Issue by jignesh87** [ilatif/active_reloader#2]
Hello  Latif,
I have read and implement your example of "php streaming and output buffering" it is very helpful.
I have one question that is it possible to use this streaming and buffering functionality with php socket.?
Is there any way to achive this.

Thank you,
Jignesh.

**Comment by ilatif** [comment]
Hi @jignesh87,

Thanks for reaching me. I think you are talking about http://www.sitepoint.com/php-streaming-output-buffering-explained/. Thanks for reading and liking it.

Regarding your question, I haven't worked with PHP Sockets yet but buffering and streaming are concepts related to networking. Networks by-default buffer response being sent so that they can sent it once it is of a good size. But in PHP Sockets if you are forcing data to be sent then it will be sent immediately.

I' am not sure yet but I guess you can easily achieve streaming functionality with PHP Sockets.

Please do try this library "active_reloader" and I hope you will like it.

Thanks.

**Comment by jignesh87** [comment]
Thank you for reply ,
i wiil try mention library.
Thanks.

**Comment by ilatif** [comment]
@jignesh87: Thanks, pleasure is all mine :-).
